using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Content.Client._RW.Lobby;
using Content.Client.Administration.UI.CustomControls;
using Content.Client.Guidebook;
using Content.Client.Stylesheets;
using Content.Client.Lobby;
using Content.Client.Lobby.UI;
using Content.Client.UserInterface.Controls;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared._RW.Humanoid.Prototypes;
using Content.Shared.Preferences;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.ContentPack;
using Robust.Shared.IoC;
using Robust.Shared.Localization;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;

namespace Content.Client._RW.Lobby.UI;

//
// SPDX-License-Identifier: AGPL-3.0-or-later
//

[GenerateTypedNameReferences]
public sealed partial class SpeciesWindow : FancyWindow
{
    private readonly DocumentParsingManager _parsingMan;
    private readonly IComponentFactory _componentFactory; // RW edit: bug-fixes #12
    private ProtoId<SpeciesPrototype> _currentSpecies;
    private readonly HumanoidCharacterProfile _profile;
    private readonly IPrototypeManager _proto;
    private readonly IResourceManager _resMan;
    private readonly LobbyUIController _uIController;

    public SpeciesWindow(SpeciesWindowContext context)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _profile = context.Profile;
        _currentSpecies = _profile.Species;
        _proto = context.PrototypeManager;
        _resMan = context.ResourceManager;
        _parsingMan = context.ParsingManager;
        _uIController = context.UIController;
        _componentFactory = IoCManager.Resolve<IComponentFactory>(); // RW edit: bug-fixes #12

        Select.OnPressed += _ => context.OnChosen(_currentSpecies);
        OnClose += context.OnClosed;

        Title = Loc.GetString("species-window-title");

        var protoList = _proto.EnumeratePrototypes<SpeciesPrototype>().Where(x => x.RoundStart).ToList();
        protoList.Sort((x, y) => string.Compare(Loc.GetString(x.Name), Loc.GetString(y.Name), StringComparison.CurrentCulture));

        AddSpeciesCategory("species-category-label-classic", SpeciesCategory.Classic, protoList);
        AddSpeciesCategory("species-category-label-unusual", SpeciesCategory.Unusual, protoList);
        AddSpeciesCategory("species-category-label-special", SpeciesCategory.Special, protoList);
        AddSpeciesCategory("species-category-label-sponsor", SpeciesCategory.Sponsor, protoList);

        SelectSpecies(_profile.Species);
    }

    private void AddSpeciesCategory(string labelKey, SpeciesCategory category, IEnumerable<SpeciesPrototype> prototypes)
    {
        var categoryPrototypes = prototypes.Where(x => x.Category == category).ToList();
        if (categoryPrototypes.Count == 0)
            return;

        AddLabel(Loc.GetString(labelKey));

        foreach (var item in categoryPrototypes)
        {
            var button = new SpeciesButton(item.ID)
            {
                HorizontalExpand = true,
                ToggleMode = true,
                Pressed = _profile.Species == item.ID,
                Text = Loc.GetString(item.Name),
                Margin = new Thickness(5f, 5f),
            };
            button.OnToggled += args =>
            {
                if (!args.Pressed)
                    return;

                SelectSpecies(item.ID);
            };

            SpeciesContainer.AddChild(button);
        }
    }

    private void AddLabel(string text)
    {
        var container = new BoxContainer()
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin = new Thickness(5f, 5f),
        };

        var label = new Label()
        {
            Text = text,
            StyleClasses = { StyleClass.LowDivider },
            Margin = new(2f, 2f),
            HorizontalAlignment = HAlignment.Center,
        };

        var separator = new HSeparator()
        {
            Margin = new(2f, 2f, 2f, 4f),
        };

        container.AddChild(label);
        container.AddChild(separator);

        SpeciesContainer.AddChild(container);
    }

    private void SelectSpecies(ProtoId<SpeciesPrototype> protoId)
    {
        DetailInfoContainer.DisposeAllChildren();

        foreach (var item in SpeciesContainer.Children)
        {
            if (item is not SpeciesButton button)
                continue;

            button.Pressed = protoId == button.Proto;
        }

        var proto = _proto.Index(protoId);
        _currentSpecies = protoId;

        JobPrototype? jobProto = null;
        var highJob = _profile.JobPriorities.FirstOrDefault(x => x.Value == JobPriority.High);
        if (!string.IsNullOrEmpty(highJob.Key) && _proto.TryIndex(highJob.Key, out var job))
            jobProto = job;

        var previewProfile = _profile;
        previewProfile = previewProfile.WithSpecies(protoId);
        previewProfile = previewProfile.WithBodyType(GetPreviewBodyType(proto, previewProfile.BodyType));

        var skin = proto.SkinColoration;
        var strategy = _proto.Index<SkinColorationPrototype>(skin).Strategy;
        var color = _profile.Appearance.SkinColor;
        switch (strategy.InputType)
        {
            case SkinColorationStrategyInput.Unary:
                try
                {
                    var tone = strategy.ToUnary(color);
                    color = strategy.FromUnary(tone);
                }
                catch (InvalidOperationException)
                {
                    color = Color.White;
                }
                break;

            case SkinColorationStrategyInput.Color:
                color = strategy.ClosestSkinColor(color);
                break;
        }

        previewProfile = previewProfile.WithCharacterAppearance(previewProfile.Appearance.WithSkinColor(color));

        var mob = _uIController.LoadProfileEntity(previewProfile, jobProto, ClothingDisplayMode.HideAll);
        Mob.SetEntity(mob);

        var loadoutMob = _uIController.LoadProfileEntity(previewProfile, jobProto, ClothingDisplayMode.ShowAll);
        JobLoadout.SetEntity(loadoutMob);

        Select.Disabled = _profile.Species == protoId;

        var prosConsContainer = new BoxContainer()
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin = new Thickness(5f, 5f),
            MaxWidth = 380f,
        };

        var prosConsLabel = new RichTextLabel()
        {
            Text = Loc.GetString("ui-species-pros-cons"),
            StyleClasses = { StyleClass.LowDivider },
            Margin = new(2f, 2f),
        };

        var separator = new HSeparator()
        {
            Margin = new(2f, 2f, 2f, 4f),
        };

        prosConsContainer.AddChild(prosConsLabel);
        prosConsContainer.AddChild(separator);
        DetailInfoContainer.AddChild(prosConsContainer);

        var generatedTraits = SpeciesDescriptionGenerator
            .Generate(proto, _proto, _componentFactory)
            .ToList();

        var hasTraits = false;

        if (proto.Pros.Count > 0)
        {
            foreach (var item in proto.Pros)
            {
                AddTraitLabel(prosConsContainer, Loc.GetString(item), SpeciesTraitKind.Pro);
                hasTraits = true;
            }
        }

        foreach (var trait in generatedTraits.Where(t => t.Kind == SpeciesTraitKind.Pro))
        {
            AddTraitLabel(prosConsContainer, trait.Text, SpeciesTraitKind.Pro);
            hasTraits = true;
        }

        if (proto.Pros.Count > 0 || generatedTraits.Any(t => t.Kind == SpeciesTraitKind.Pro))
            prosConsContainer.AddChild(new Control() { MinHeight = 8f });

        if (proto.Special.Count > 0)
        {
            foreach (var item in proto.Special)
            {
                AddTraitLabel(prosConsContainer, Loc.GetString(item), SpeciesTraitKind.Neutral);
                hasTraits = true;
            }
        }

        foreach (var trait in generatedTraits.Where(t => t.Kind == SpeciesTraitKind.Neutral))
        {
            AddTraitLabel(prosConsContainer, trait.Text, SpeciesTraitKind.Neutral);
            hasTraits = true;
        }

        if (proto.Special.Count > 0 || generatedTraits.Any(t => t.Kind == SpeciesTraitKind.Neutral))
            prosConsContainer.AddChild(new Control() { MinHeight = 8f });

        if (proto.Cons.Count > 0)
        {
            foreach (var item in proto.Cons)
            {
                AddTraitLabel(prosConsContainer, Loc.GetString(item), SpeciesTraitKind.Con);
                hasTraits = true;
            }
        }

        foreach (var trait in generatedTraits.Where(t => t.Kind == SpeciesTraitKind.Con))
        {
            AddTraitLabel(prosConsContainer, trait.Text, SpeciesTraitKind.Con);
            hasTraits = true;
        }

        if (!hasTraits)
        {
            prosConsContainer.AddChild(new RichTextLabel
            {
                Text = Loc.GetString("ui-species-no-pros-cons"),
                Margin = new(4f),
            });
        }

        // RW edit start: bug-fixes #12
        AddLoreSection(proto);
    }

    private static void AddTraitLabel(BoxContainer container, string text, SpeciesTraitKind kind)
    {
        var prefix = kind switch
        {
            SpeciesTraitKind.Pro => "[color=#13f244]- ",
            SpeciesTraitKind.Con => "[color=#d63636]- ",
            _ => "- ",
        };

        var suffix = kind == SpeciesTraitKind.Neutral ? "" : "[/color]";

        container.AddChild(new RichTextLabel
        {
            Text = prefix + text + suffix,
            StyleClasses = { StyleClass.LowDivider },
            Margin = new(4f, 2f),
        });
    }

    private void AddLoreSection(SpeciesPrototype proto)
    {
        if (!proto.Description.HasValue)
            return;

        if (!_resMan.TryContentFileRead(proto.Description.Value, out var file))
            return;

        var container = CreateSection(Loc.GetString("ui-species-lore-title"), compact: true);
        DetailInfoContainer.AddChild(container);

        var loreContainer = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin = new(4f, 0f),
        };
        container.AddChild(loreContainer);

        using (file)
        using (var reader = new StreamReader(file))
        {
            var text = PrepareLoreText(reader.ReadToEnd(), Loc.GetString(proto.Name));
            _parsingMan.TryAddMarkup(loreContainer, text);
        }
    }

    private static string PrepareLoreText(string text, string speciesName)
    {
        text = ReplaceSpeciesTitle(text, speciesName);

        const string openTag = "<Document>";
        const string closeTag = "</Document>";
        var openIdx = text.IndexOf(openTag, StringComparison.OrdinalIgnoreCase);
        if (openIdx >= 0)
        {
            var start = openIdx + openTag.Length;
            var closeIdx = text.IndexOf(closeTag, start, StringComparison.OrdinalIgnoreCase);
            if (closeIdx >= 0)
                text = text[start..closeIdx];
        }

        return text.TrimStart('\r', '\n', ' ', '\t');
    }

    private static string ReplaceSpeciesTitle(string text, string speciesName)
    {
        var lines = text.Split('\n');
        for (var i = 0; i < lines.Length; i++)
        {
            var trimmed = lines[i].TrimStart();
            if (!trimmed.StartsWith('#') || trimmed.StartsWith("##"))
                continue;

            var indent = lines[i][..^trimmed.Length];
            lines[i] = indent + "# " + speciesName;
            break;
        }

        return string.Join('\n', lines);
    }

    private static BoxContainer CreateSection(string title, bool compact = false)
    {
        var container = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin = new Thickness(5f, 5f),
            MaxWidth = 380f,
        };

        container.AddChild(new RichTextLabel
        {
            Text = title,
            StyleClasses = { StyleClass.LowDivider },
            Margin = new(2f, 2f),
        });

        container.AddChild(new HSeparator
        {
            Margin = compact ? new(2f, 2f, 2f, 0f) : new(2f, 2f, 2f, 4f),
        });

        return container;
    }
    // RW edit end: bug-fixes #12

    private string GetPreviewBodyType(SpeciesPrototype species, string currentBodyType)
    {
        var validBodyTypes = species.BodyTypes
            .Where(id => _proto.TryIndex<BodyTypePrototype>(id, out var bodyType) &&
                !bodyType.SexRestrictions.Contains(_profile.Sex.ToString()))
            .ToList();

        if (validBodyTypes.Contains(currentBodyType))
            return currentBodyType;

        if (validBodyTypes.Count > 0)
            return validBodyTypes[0];

        return species.BodyTypes.FirstOrDefault() ?? currentBodyType;
    }

    private sealed class SpeciesButton(string proto) : Button
    {
        public readonly string Proto = proto;
    }
}

public sealed record SpeciesWindowContext(
    HumanoidCharacterProfile Profile,
    IPrototypeManager PrototypeManager,
    IResourceManager ResourceManager,
    DocumentParsingManager ParsingManager,
    LobbyUIController UIController,
    Action<ProtoId<SpeciesPrototype>> OnChosen,
    Action OnClosed);
